### ISSUE TITLE
完了呀,后面谁来维护这个项目

### ISSUE THREAD

**Issue by tianyilt** [tianyilt/ecust-CourseShare#72]

**Comment by yiyisoclever** [comment]
可以请问一下维护的话大概需要做什么工作吗？除了上传资料还需要做什么吗？
















在 2021-10-13 23:26:24，"tianyilt" ***@***.***> 写道：

1

你好呀,加一波qq好友吗

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by tianyilt** [comment]
> 可以请问一下维护的话大概需要做什么工作吗？除了上传资料还需要做什么吗？ 在 2021-10-13 23:26:24，"tianyilt" ***@***.***> 写道： 1 你好呀,加一波qq好友吗 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

兄弟,还来维护吗
